[build-system]
requires = [
  "setuptools>61"
]

[project]
name = "megadetector"
version = "5.0.21"
description = "MegaDetector is an AI model that helps conservation folks spend less time doing boring things with camera trap images."
readme = "README-package.md"
# As of 2023.10.10, PyTorch isn't installable on Python 3.12
requires-python = ">=3.9,<3.12"
license = {file = "LICENSE"}
keywords = ["camera traps", "conservation", "wildlife", "ai", "megadetector"]
authors = [
  {name = "Your friendly neighborhood MegaDetector team", email = "cameratraps@lila.science" }
]
maintainers = [
  {name = "Your friendly neighborhood MegaDetector team", email = "cameratraps@lila.science" }
]

classifiers = [
  "Programming Language :: Python :: 3",
]

dependencies = [
  # Not imported directly, but we force this version to avoid this issue:
  #
  # https://github.com/pytorch/pytorch/issues/123097
  "mkl == 2024.0",
  # To run ultralytics-yolov5, we need to use an old version of numpy, because
  # of the removal of np.int in numpy 1.24.0.  Even if we relaxed that requirement
  # or patched np.int, we definitely don't want numpy>=2.0.
  "numpy >= 1.22, < 1.24",
  "Pillow >= 9.5, <10",
  "tqdm >= 4.64.0",
  "jsonpickle >= 3.0.2",
  "humanfriendly >= 10.0",
  "matplotlib >= 3.8.0",
  "opencv-python >= 4.8.0",
  "requests >= 2.31.0",
  "pyqtree >= 1.0.0",
  "scikit-learn >= 1.3.1",
  "pandas >= 2.1.1",  
  "python-dateutil",
  "send2trash",
  # Not imported directly, but required to de-serialize some models
  "dill",
  "ultralytics-yolov5 == 0.1.1",
  "yolov9pip == 0.0.4"
  # Let ultralytics-yolov5 install torch
  # "torch >= 2.0.1",
  # "torchvision >= 0.15.2",  
  # Let the user install ultralytics if they want to use YOLOv11 models
  # ultralytics
]

[project.urls]
"Homepage" = "https://github.com/agentmorris/MegaDetector"
"Documentation" = "https://megadetector.readthedocs.io"
"Bug Reports" = "https://github.com/agentmorris/MegaDetector/issues"
"Source" = "https://github.com/agentmorris/MegaDetector"

[tool.setuptools.packages.find]
include = ["megadetector*"]

